name: Formatter
on: workflow_dispatch
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxelib --quiet install formatter

      - name: Formatting
        run: haxelib run formatter -s ./

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Formatted-Source
          path: |
            ./hxlua
            ./samples
          if-no-files-found: error
